# 

name: testrun

on:
  push:
    branches: [ master, tokoharu-test-1]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set up Kotlin
      run: |
        curl -sL https://get.sdkman.io | bash
        source "${HOME}/.sdkman/bin/sdkman-init.sh"
        sdk install kotlin
    - name: markdownify_full
      run: |
        rime
        rime help test
        mkdir tmp && cd tmp && rime_init --git && cd ..
        cd example
        rime help
        pwd
        ls
        rime markdownify_full && rime clean
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: summary.$$.md
        path: example/summary.md
    - name: pack_for_aoj
      if: always()
      run: |
        ls
        cd example
        ./pack_example_for_aoj.sh
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: packed_example.$$.zip
        path: example/packed_example.zip
